name: rest-graphql-benchmark

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: python:3.11

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --categories=dev-packages --system 
    - name: Linting
      run: |
        isort . --check
        black . --check
        flake8 .
    - name: Test with pytest
      run: |
        pytest
